services:
  node:
    build:
      context: .
      dockerfile: ./docker/node/Dockerfile
    container_name: node
    command: npm run dev
    ports:
      - target: 3000
        host_ip: 127.0.0.1
        published: 3000
        protocol: tcp
        mode: host
    volumes:
      - type: bind
        source: .
        target: /app
    environment:
      NODE_OPTIONS: "--disable-warning=ExperimentalWarning"
    tty: true
    stdin_open: true
